### PR TITLE
fix(configUpdater): search up-tree for updatable_conf options

### PR DESCRIPTION
**Pull request by nritsche**

### CODE REVIEW

**Comment by nritsche** [comment]
> This looks good to me, but can we make sure the formatting changes here are also reflected in the science run config, mostly to make the diff just involves the operational changes.

I think so, too. But should we directly add a yamllint CI check when doing this?

**Comment by andrerenard** [comment]
Yes a yamllint check is something I've been meaning to add to the CI process.  It might just require a fair bit of clean up of some of the other config files.  And when we do we should add it to the "pre_commit" clean up script as well.

**Comment by james-s-willis** [comment]
Looks good to me. I've tested it on `csDg9` too and it runs fine.

**Comment by james-s-willis** [comment]
@nritsche I think the unit tests just need updating

**Comment by andrerenard** [comment]
I'm afraid I just realised I need this for a test tomorrow.  I'm going to pull it in without passing CI, since the CI server seems to be down again...

**Comment by jrs65** [comment]
@andrerenard @nritsche can we please not just merge things when the CI server is down? Or at the very least can someone please run the tests themselves? This PR breaks almost all of the Python unit tests and now I'm having to figure out how to fix it.

**Pull request merged**
