### PR TITLE
fix negative timespec bug #288

### PR DESCRIPTION
**Pull request by nritsche**

### CODE REVIEW

**Comment by andrerenard** [comment]
Is this still being targeted for this release?    What's still required (if anything) @nritsche, @jrs65 ?   At the very least, we need fix the merge problems.

**Comment by jrs65** [comment]
I think not for this release.

**Comment by andrerenard** [comment]
@jrs65 Is this something we want to target finishing for the next release?

**Comment by jrs65** [comment]
Probably. In theory all the time related code do with a refactor, and wanting to do that is why this never got finished up. I don't think it brings any actual science returns though, so we can put it on the list but with a low priority.

**Comment by nritsche** [comment]
Replaced by #789

**Pull request closed without merging**
