### PR TITLE
Add a missing Python dependency on `requests`

### PR DESCRIPTION
**Pull request by cubranic**

### CODE REVIEW

**Comment by cubranic** [comment]
BTW, how did this not trip up the CI server? The virtualenv used for testing is not transient?

**Comment by jrs65** [comment]
Which code needs `requests`? Maybe it's not run through the CI server.

**Comment by cubranic** [comment]
The following files contain "import requests":

- scripts/gps_yaml_to_json.py
- python/kotekan/runner.py
- python/scripts/kernel_utilization.py
- python/scripts/rfi_receiver.py
- python/kotekan/scripts/ctl.py

**Comment by cubranic** [comment]
Specifically, it's used in the test runner to execute REST commands: see [line 93](https://github.com/kotekan/kotekan/blob/develop/python/kotekan/runner.py#L93)

**Comment by jrs65** [comment]
Weird that it didn't get caught then.

**Pull request merged**
