### PR TITLE
Correct type of primary weight accumulation vector to float.

### PR DESCRIPTION
**Pull request by james-s-willis**

### CODE REVIEW

**Review by andrerenard — APPROVED** [review]

**Review by jrs65 — APPROVED** [review]

**Comment by jrs65** [comment]
Do we have any idea why the macOS builds are failing?

**Comment by andrerenard** [comment]
It looks like it's trying to run two sets of CI tests for everything.   One of them appears to be passing and the other isn't...  I'm inclined to think this is a github bug of some kind.

**Comment by nritsche** [comment]
> It looks like it's trying to run two sets of CI tests for everything. One of them appears to be passing and the other isn't... I'm inclined to think this is a github bug of some kind.

```
GitHub Actions has encountered an internal error when running your job.
```

**Comment by andrerenard** [comment]
It's passing on one of the two MacOS tests, I'd be ok with merging this.  But we need to decide first if this is something we want to merge into the tagged release.

**Pull request merged**
