### PR TITLE
Add sidebar to show trackers_current info

### PR DESCRIPTION
**Pull request by Jintao-Xu**
Add a sidebar to display tracker current info

### CODE REVIEW

**Comment by Jintao-Xu** [comment]
image
image

**Comment by Jintao-Xu** [comment]
Since I cannot trigger redraw properly after using many online solutions, I added this new sidebar to display trackers. It works fine, and interaction goes smoothly.

It is possible if we also want each stage node as a button to control tracker display on the right.

**Comment by andrerenard** [comment]
I think it would be good to make clicking the node in the graph open the item in the side bar.   I suggest we also exclude the stages which haven't been clicked on.  In some of our pipelines we have 50+ stages, and it could get hard to find the item you want in the side bar. 

In terms of the sidebar format.   I would like to see the current value as well, and also display the units.    It might also be worth creating a standard format for all the numbers that doesn't require a line for each number.   e.g.

```
fill_frame_time:  <cur_value> <unit> (<avg>, <std>, <min>, <max>).
```
And then include a legend to indicate the order of values.   Although option would be to generate a table with a header. 

Also I would like to see maybe the first 2 stats trackers in the node on the graph itself, just showing the name, current value, and unit.

**Comment by Jintao-Xu** [comment]
image
image

**Review by andrerenard — APPROVED** [review]
This all looks great!  Long term it looks like it will make sense to use the KotekanTrackers for CPU utilization, and that might simplify some of the code here, but that's for another PR.   For now we can merge this, and just focus on displaying the historical data.

**Pull request merged**
