### PR TITLE
config(recv): add valve processes to protect from backups in bufferSend

### PR DESCRIPTION
**Pull request by jrs65**

### CODE REVIEW

**Review by andrerenard — APPROVED** [review]
This looks good to me.  Just to check is there enough RAM on that node to support the extra buffers?

**Comment by jrs65** [comment]
Yeah. They're tiny compared to the rest (e.g. the length 4096 *full N2* buffer!)

**Review by andrerenard — COMMENTED** [review]
Actually might it make more sense to make the valve buffers the larger of the two in terms of splitting up the buffer depth?   The valve process generally moves things from the input buffer very quickly, but will start dropping as soon as the output buffer is full.

**Comment by jrs65** [comment]
I thought about that, but the issue is that the upstream buffers all feed into the write processes. So I think you do actually want it like this.

**Pull request merged**
