### PR TITLE
Print iwyu diff and run on PRs

### PR DESCRIPTION
**Pull request by nritsche**

### CODE REVIEW

**Review by andrerenard — APPROVED** [review]
This works nicely!   Getting the diff that is.  This latest change we still need to see about.

**Comment by nritsche** [comment]
It printed the diff, but then it exited with success...

**Comment by andrerenard** [comment]
You could save the return code from iwyu and return that with `exit`.

**Comment by andrerenard** [comment]
You might need to do something like `(exit $exit_code)` to generate the return code the way github wants it.

**Comment by andrerenard** [comment]
I'm not a big fan of that auto commit.  That means we'll then have a broken commit in develop when iwyu does something wrong, and because of our branch rules means we'll still have to fix it in another PR branch.  I would just dump the diff, and then we can clean up develop in a PR manually.

**Pull request merged**
