### PR TITLE
Update polyco script

### PR DESCRIPTION
**Pull request by tristpinsm**
We are approaching a time when the 26m will be operational again and we can resume testing/start observations with pulsar gating, so I improved the script that generates and sends gating configs. It should now be able to generate the config update and send it as well as disable gating all within the script.

### CODE REVIEW

**Comment by andrerenard** [comment]
Is this being targeted for this release, or can we delay getting it in until after the current deployment.

**Comment by tristpinsm** [comment]
This only touches the polyco python script, so it doesn't need to be included in the release, but it also has no effect on kotekan.

**Comment by andrerenard** [comment]
@tristpinsm any objections to me merging this in now?

**Comment by tristpinsm** [comment]
@andrerenard no objections. I've been using it to enable/disable gating a few times now and no more bugs cropped up.

**Pull request merged**
