### PR TITLE
Fix RFIFrameDrop dataset state registration

### PR DESCRIPTION
**Pull request by nritsche**
If the `enable` endpoint is called befor the `threshold`-one, an uninitialized state_ptr is accessed -> segfault.
Fix: The `enable` endpoint callback uses an empty vector if the state is not available yet.

I would have preferred to create an initial dummy dataset state in the constructor, but it would have to life in the datasetManager and get registered with comet.

### CODE REVIEW

**Review by andrerenard — COMMENTED** [review]
Could this also fail if `rest_thresholds_callback()` gets called first and tries to call: `state_ptr->get_enabled()` ?

**Comment by nritsche** [comment]
> Could this also fail if `rest_thresholds_callback()` gets called first and tries to call: `state_ptr->get_enabled()` ?

Good point.

**Comment by andrerenard** [comment]
Did you want me to review this as is, or were you also going to fix the other case?   Another option might just be to generate an initial state in the constructor before calling the callbacks?

**Comment by nritsche** [comment]
> Did you want me to review this as is, or were you also going to fix the other case? Another option might just be to generate an initial state in the constructor before calling the callbacks?

Oups, somehow I failed to push.
I would have preferred having a dummy state, too. But it would end up in comet and chimedb.

**Review by andrerenard — APPROVED** [review]

**Pull request merged**
