### PR TITLE
Update ctl script

### PR DESCRIPTION
**Pull request by tristpinsm**
Some fixes to make the kotekan_ctl script more usable and installation work better. The timeouts may need to be tweaked, I wasn't sure how long would be needed.

### CODE REVIEW

**Comment by nritsche** [comment]
Great, thanks Tristan!
I'm not sure if the scripts directory needs an __init__ file

**Comment by tristpinsm** [comment]
In python 3 (on my laptop) the script gets properly installed without the `__init__.py`, but when I tried it on a receiver node with python 2 it was unable to find the script module without that file...

**Comment by nritsche** [comment]
Oh I see, ctl.py is actually not a script, but a module. I got confused by the directory name.

**Comment by tristpinsm** [comment]
Yeah, it's a bit confusing how this `load_entry_points` thing works. I'll go ahead and merge then.

**Comment by andrerenard** [comment]
@tristpinsm this looks good!  thanks for adding this.  just please remember to squash merge, and move the description to the squash commit.

**Pull request merged**
