### PR TITLE
Add missing telescope section to CHIME configs

### PR DESCRIPTION
**Pull request by andrerenard**

### CODE REVIEW

**Review by nritsche — COMMENTED** [review]
LGTM

**Comment by andrerenard** [comment]
> LGTM

I'm not sure what you mean by this comment @nritsche ?

**Comment by nritsche** [comment]
> > LGTM
> 
> I'm not sure what you mean by this comment @nritsche ?

looks good to me

I'll leave it to a second or third reviewer to approve, though.

**Comment by james-s-willis** [comment]
I realised why I wasn't getting this error. I had it come up before and I added `num_local_freq` to the relevant configs. But the changes look okay to me.

**Review by james-s-willis — APPROVED** [review]

**Comment by andrerenard** [comment]
I'm going to merge this in to get things going.  If there are any changes to be made we'll open a new PR.

**Pull request merged**
