### PR TITLE
Fix bug where stacked weights can be set to NaN when should be 0

### PR DESCRIPTION
**Pull request by tristpinsm**

### CODE REVIEW

**Comment by tristpinsm** [comment]
I've checked that this fixes the issue running on my laptop using the `test_pattern_freq` mode of `fakeVis` to generate data with zero weights.

**Comment by jrs65** [comment]
Great. Can you fix the build failure (formatting)?

**Comment by tristpinsm** [comment]
oh I didn't even realize we had that...

**Comment by jrs65** [comment]
Okay. Thanks Tristan. Looks good to me, but I'm not sure what the current merge/deploy plan is. @andrerenard should decide what to do with this.

**Comment by nritsche** [comment]
@tristpinsm if you install clang-format 9, you can do `make clang-format` in `kotekan/build`

**Comment by tristpinsm** [comment]
ah ok! thanks for the tip, that'll save me some useless commits

**Pull request merged**
