### PR TITLE
Type name in Python 3 should be a string not bytes

### PR DESCRIPTION
**Pull request by cubranic**

### CODE REVIEW

**Comment by andrerenard** [comment]
What is this trying to fix?  It seems like it's broken the boost tests in the current form.

**Comment by cubranic** [comment]
I don’t see how that is possible, it changes a method in a module that is only included from `tests/test_frb_post_process.py`, and another module only used by `tests/test_psr_post_process.py`.

BTW, those tests are skipped on the CI server because it doesn’t have the captured buffer files to use as inputs, and it’s not run with the option to use the more time-consuming method. That’s why the bug was not discovered before.

**Comment by andrerenard** [comment]
Looks like it's passing now, so it must have been something else going wrong with the CI.   If @nritsche can review, then we can merge this in.

**Comment by nritsche** [comment]
> What is this trying to fix? It seems like it's broken the boost tests in the current form.

I also don't know what this is trying to fix.

**Comment by jrs65** [comment]
It sounds like I can merge this, right @cubranic ?

**Comment by jrs65** [comment]
This seems low risk. I'm going to approve and merge it just to get it off the queue.

**Review by jrs65 — APPROVED** [review]

**Comment by cubranic** [comment]
No please wait, it hasn’t been tested recently.

**Comment by jrs65** [comment]
Too late!

**Pull request merged**
