### PR TITLE
Read debug frames

### PR DESCRIPTION
**Pull request by tristpinsm**
Added the ability to read back GPU buffer dumps in python.

### CODE REVIEW

**Comment by jrs65** [comment]
@tristpinsm this looks great. However, could you rebase only the relevant commits on top of the current `develop` branch? I think you've started this from a non merged branch and thus it looks like there's an extra 84 commits in addition to the five that look useful. It makes it much easier to review.

**Comment by jrs65** [comment]
You'll need to do the rebase and then force push to replace this branch.

**Comment by tristpinsm** [comment]
Oh, ok. Is this because commits are being squashed into one after the PR?

**Comment by jrs65** [comment]
> Oh, ok. Is this because commits are being squashed into one after the PR?

Partly yes. Though you'd be missing merge commits if you didn't do this and we just used a normal merge. Generally it's way better to start a fresh branch from develop every time you start to develop something new unless you really need something else in a different branch. Thanks!

**Pull request merged**
