### PR TITLE
Fix rfi band calc

### PR DESCRIPTION
**Pull request by james-s-willis**
I've added the fixes to the script for both `rfi_band` calculation and using NaN in the `waterfall` arrays instead of `-1`. The only issue I have is that there were commented out parts of the code which had `waterfall` initialised to `np.nan` and for some reason Jacob didn't use them...

### CODE REVIEW

**Review by jrs65 — APPROVED** [review]
These changes look good to me. However, it would be good to check to see if it actually makes the values exported to prometheus more sane. Is there a way of doing that without interrupting the current  service?

**Comment by james-s-willis** [comment]
That's the issue I don't know of a way to test this without it going live on `carillon`.

**Comment by jrs65** [comment]
I guess we should wait until deployment week then?

**Comment by james-s-willis** [comment]
Yeah, that it was what I was thinking.

**Comment by james-s-willis** [comment]
@jrs65 I've added that fix now. I think it's good to be merged.

**Pull request merged**
